language: node_js

node_js:
  - "12.7.0"

os:
  - osx

osx_image: xcode9.3

cache:
  yarn: true

install:
  - yarn

script:
  - yarn dlgeo
  - yarn distmac
  - USE_HARD_LINKS=false yarn distwin
  - yarn distlinux
  - ls -la dist

deploy:
  provider: releases
  api_key:
    secure: "OtI74uPUQvLasnFy0pfRxpWaltUiNYGgZ+o/1tEuxnaktMfLLLTnSba7GLhl4jzJXwvg5bEMQL1QVQpp1vtalX871Ey0m7tV7X83GVuaEA/ToE7q2lazErCH69e5/1M/SpHbIDWvC7QO5oyJNv7SI0giQ1H+YDjgrIHscEVBme5f8ZCeUoxw7wKVQPf8NJAVYJYmfG7Huu+trtNuzmId10Drs33jo2NNB3fW12Fp4sJbdeHEe1pVaBsChaK8f6hnZdrvPvc5XbKZfDMEgyEp1mrRUH7whNmtS/uoRbhaUEJpZCuu0COnRricxa2lntOsZRa5E2gvfIlNpgLHfV4pcqkCCBbJa0QcOQYciZSEtXUCKicWu05zqT80eHlRXoKXAXeN/jRwJk+tCs7K8jeLwM1FBg3zKmKhKdB9Am8yXNKTwucuVv+NEYsUUwW8SYXV59aKkGZRZ/qT/sIuq6RlKq/Az92GoFlPd+NsUE5gCFYwZb1OuHMaYvbcjhaz7cYXL6DHAiJ60PphQAUocf7GdoUwVFVdeI5CC2x9m4Nul371oBkcdHlnPvGIVGgeh5MvRedCUBU/FEJZiQC9m/7bdJ/zVEiOV0loIteEaUV7m9pdfkJwvLw95nP+N2LKMMIURyhEq94CgW2SLCS5wn2CRjcY+G3/DooHbxkWILdXAzw="
  file_glob: true
  file:
    - "dist/Mellow Setup*.exe"
    - "dist/Mellow*.dmg"
    - "dist/Mellow*.AppImage"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
